### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by jkhaui** [peritext/scholar-draft#40]
Hi,

I'm very keen to try this out but I can't figure out from the documentation how to use scholar-draft. Is it an NPM package? Am I just supposed to import `Editor` from `scholar-draft` and use it as I would like the normal draft.js Editor (albeit with the additional features)?

If you could please provide some demo examples that would be great. I'm not familiar with storybook either, so I don't quite get the implementation in there

**Comment by robindemourat** [comment]
Hi,

> Is it an NPM package?

Yes, you can install it through `npm install --save scholar-draft`. But this experimental module has not been stabilized so a complete doc is not there yet, sorry for that.

> Am I just supposed to import Editor from scholar-draft and use it as I would like the normal draft.js Editor (albeit with the additional features)?

Yes, you can look at minimal up-to-date implementation examples in the `stories` folder, like [this one](https://github.com/peritext/scholar-draft/blob/master/stories/EditorExample.js).

Concerning storybook, after cloning the repo you can simply run `npm run storybook` to see them running and possibly play with the example by editing the files in the `stories` folder.

Anyway that's a very good point, keeping this open until the documentation is updated.

**Comment by jkhaui** [comment]
Thanks for explaining the WIP status, that makes sense. I sort of managed to get it running by installing the npm package, copying over the storybook examples for the editor and then installing any missing packages.

However, I couldn't get footnotes working? That's actually the feature I'm most interested in. I recently developed a footnoting system using contenteditable, but draft js seems a much better platform to build on. If I can, I'd love to help contribute to the footnoting feature (if it hasn't already been implemented)

**Comment by robindemourat** [comment]
Well footnotes normally work (or don't they ? ;)). You can see `scholar-draft` in use in [this online application](https://peritext.github.io/ovide/) ([source code here](https://github.com/peritext/ovide)) or in [this project](https://github.com/medialab/fonio/blob/master/src/components/SectionEditor/SectionEditor.js) for examples of real-life implementations.

Hope that will help. Draft-js is great indeed, you may want to look at stable packages such as [Draftail](https://www.draftail.org/) which propose higher-level APIs (this one does not handle footnotes though, hence this project :))

And yes do not hesitate to contribute !

**Comment by jkhaui** [comment]
Sorry Robin, yes, footnotes work great! It was my fault with the setup. I'm becoming more familiar with draft-js and scholar-draft and have to say, this is really amazing. Great stuff.

That being said - I've noticed a bug with footnote number ordering. I'll close this issue and open a new one to explain :)
